id: I66EBE4B0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-02-21T13:26:58+00:00'
last_modified: '2022-06-15T14:00:46.415654+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG25918
  title: དཔལ་ལྡན་ས་སྐྱའི་གདུང་རབས་ལོ་རྒྱུས་ལས་གསར་བུ་བ་རྣམས་ཀྱི་ལྟ་བའི་མེ་ལོང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    048B:
      image_group_id: I1KG26062
      title: Volume 1 of dpal ldan sa skya'i gdung rabs lo rgyus las gsar bu ba rnams
        kyi lta ba'i me long_/
      total_pages: 118
      order: 1
      base_file: 048B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
